name: Python Tests

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]  

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest and generate Report
      run: |
        pytest --cov=app --cov-report=html:cov Tests/
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: cov
    - name: Calculate Test Coverage
      id: coverage
      run: |
        python - <<EOF
        from bs4 import BeautifulSoup

        with open('cov/index.html', 'r') as file:
            soup = BeautifulSoup(file, 'html.parser')
            coverage = soup.find('span', class_='pc_cov').get_text()
            print(coverage)
        with open("coverage.txt", "w") as coverage_file:
            coverage_file.write(coverage)
        EOF
        echo "Coverage report calculated"
        echo "COVERAGE_REPORT=$(cat coverage.txt)" >> $GITHUB_ENV
    - name: Check Test Coverage
      run: |
        coverage=$COVERAGE_REPORT
        coverage=${coverage%\%}
        if [[ -n "$coverage" && $coverage -ge 1 ]]; then
          echo "Test coverage is greater than or equal to 1%"
        else
          echo "Test coverage is less than 1%. Aborting the workflow."
          exit 1
        fi
